# Generated by Django 6.0 on 2026-01-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='ai_decisions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
