# Generated by Django 6.0 on 2026-01-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meeting_jitsi_room'),
        ('minutes', '0002_minutes_ai_decisions_minutes_ai_generated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True)),
                ('decisions_json', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('pipeline_version', models.CharField(blank=True, default='v1', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_output', to='meetings.meeting')),
            ],
        ),
    ]
