# Generated by Django 6.0 on 2026-01-13 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0003_aioutput'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aioutput',
            options={'ordering': ['-generated_at'], 'verbose_name': 'AI Output', 'verbose_name_plural': 'AI Outputs'},
        ),
        migrations.AlterModelOptions(
            name='minutes',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Minutes', 'verbose_name_plural': 'Minutes'},
        ),
        migrations.AddField(
            model_name='minutes',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='minutes',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aioutput',
            name='summary_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='ai_decisions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='discussion_points',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
