# -*- coding: utf-8 -*-
"""face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjDfcUBCHng-_p0JOonIT0F7vciodWpz
"""

# face_recognition.py

# face.py

from pathlib import Path
from deepface import DeepFace
from scipy.spatial.distance import cosine
import pickle

THRESHOLD = 0.68

# تحديد مسار الملف الحالي
BASE_DIR = Path(__file__).resolve().parent

# تحميل قاعدة بيانات الوجوه
with open(BASE_DIR / "face_embeddings.pkl", "rb") as f:
    FACE_DB = pickle.load(f)

def verify_face(image_path: str, authorized_users: list):
    """
    image_path: path to image
    authorized_users: list of user names or IDs
    """

    embedding = DeepFace.represent(
        img_path=image_path,
        model_name="ArcFace",
        enforce_detection=True
    )[0]["embedding"]

    for user in authorized_users:
        stored_embedding = FACE_DB.get(user)
        if stored_embedding is None:
            continue

        similarity = 1 - cosine(embedding, stored_embedding)

        if similarity >= THRESHOLD:
            return {
                "approved": True,
                "user": user,
                "confidence": round(similarity, 2)
            }

    return {
        "approved": False,
        "user": None,
        "confidence": 0.0
    }
