# Generated by Django 6.0 on 2026-01-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10),
        ),
    ]
