# Generated by Django 6.0 on 2026-01-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_attendee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='face_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='jitsi_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='jitsi_room',
            field=models.CharField(default='default_room', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='require_face_verification',
            field=models.BooleanField(default=True),
        ),
    ]
