# Generated by Django 6.0 on 2026-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_attendee_confidence_attendee_face_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='jitsi_room',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
