# Generated by Django 6.0 on 2026-01-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meeting_jitsi_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='join_early_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='join_late_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='meeting',
            name='mode',
            field=models.CharField(choices=[('online', 'Online Meeting'), ('upload', 'Upload Meeting'), ('both', 'Online + Upload')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
