# Generated by Django 6.0 on 2026-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_ends_at_meeting_join_early_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcript_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
