# Generated by Django 6.0 on 2026-01-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assignee_remove_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('assigned', 'Assigned'), ('done', 'Done')], default='todo', max_length=15),
        ),
    ]
