# Generated by Django 6.0 on 2026-01-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.TextField()),
                ('justification', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score from AI model (0-1)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('minutes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='minutes.minutes')),
            ],
        ),
    ]
