# Generated by Django 6.0 on 2026-01-11 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meeting_jitsi_room'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='justification',
            new_name='transcript',
        ),
        migrations.RemoveField(
            model_name='record',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='record',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='record',
            name='minutes',
        ),
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='record',
            name='meeting',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='meetings.meeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_recordings', to=settings.AUTH_USER_MODEL),
        ),
    ]
